# Generated by Django 5.0.4 on 2024-04-13 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEffectiveness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectiveness', models.CharField(choices=[('super_effective', 'Super Effective'), ('not_effective', 'Not Effective')])),
                ('base_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectiveness_relations', to='app_types.type')),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_by_relations', to='app_types.type')),
            ],
            options={
                'unique_together': {('base_type', 'target_type')},
            },
        ),
    ]
