# Generated by Django 5.0.4 on 2024-04-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeeffectiveness',
            name='effectiveness',
            field=models.CharField(choices=[('super_effective', 'Super Effective'), ('less_effective', 'Less Effective'), ('not_effective', 'Not Effective'), ('takes_more_damage', 'Takes More Damage'), ('takes_less_damage', 'Takes Less Damage'), ('receives_no_damage', 'Receives No Damage')], max_length=20),
        ),
    ]
