# Generated by Django 5.0.4 on 2024-04-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_types', '0002_alter_typeeffectiveness_effectiveness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeeffectiveness',
            name='effectiveness',
            field=models.CharField(choices=[('super_effective', 'Does x2.0 Damage'), ('less_effective', 'Does x0.5 Damage'), ('not_effective', 'Does x0.0 Damage'), ('takes_more_damage', 'Takes x2.0 Damage'), ('takes_less_damage', 'Takes x0.5 Damage'), ('receives_no_damage', 'Takes x0.0 Damage')], max_length=20),
        ),
    ]
