# Generated by Django 5.0.4 on 2024-04-13 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_moves', '0001_initial'),
        ('app_pokemoninfo', '0001_initial'),
        ('app_teampokemon', '0001_initial'),
        ('app_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosenmoves',
            name='team_pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_moves', to='app_teampokemon.teampokemon'),
        ),
        migrations.AddField(
            model_name='learnablemoves',
            name='move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_moves.move'),
        ),
        migrations.AddField(
            model_name='chosenmoves',
            name='learnable_move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_moves', to='app_pokemoninfo.learnablemoves'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='pokemons', to='app_types.type'),
        ),
        migrations.AddField(
            model_name='learnablemoves',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pokemoninfo.pokemon'),
        ),
        migrations.AlterUniqueTogether(
            name='learnablemoves',
            unique_together={('pokemon', 'move')},
        ),
    ]
