# Generated by Django 5.0.4 on 2024-04-13 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_pokemoninfo', '0001_initial'),
        ('app_teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pokemoninfo.pokemon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='app_teams.team')),
            ],
        ),
    ]
